#!/bin/bash

PKGDIR="$FPKG_ROOT/pkg"
buildopts=""
case $1 in
	--query|--list) if [ -f $PKGDIR/build-$1.sh ]; then echo "$1 from source"; fi ;;
	*) while [ ! -z "$1" ]; do
		buildopts="$buildopts" $PKGDIR/build-$1.sh
	shift
	done ;;
esac

