#!/bin/bash
_PKGDIR="$FPKG_ROOT/var/pkg"
_GITDIR="$FPKG_ROOT/var/fpkg/git"
REPO="https://github.com/Ohio2/frepo.git"
_usesha=no
_lock="/tmp/lock"
if [ -f $_lock ]; then
	echo "Error 5"
	exit 5
fi
touch $_lock
if [ ! -d $_GITDIR ]; then
	git clone $REPO $_GITDIR
fi
cd $_GITDIR
git pull
cd $OLDPWD
if [ ! -d $_PKGDIR ]; then
	mkdir -pv $_PKGDIR
fi
case $1 in
	sha) while [ ! -z "$2" ]; do [ $_usesha = yes | $_usesha = true ]; PKGDIR=$_PKGDIR shapkg "$2"; shift; done ;;
	i|install) while [ ! -z "$2" ]; do PKGDIR=$_PKGDIR GITDIR=$_GITDIR spkg "$2" ; PKGDIR=$_PKGDIR ipkg "$2" ; PKGDIR=$_PKGDIR GITDIR=$_GITDIR spkg < $2.d ; PKGDIR=$_PKGDIR ipkg < $2.d ; shift; done ;;
	u|update) while [ ! -z "$2" ]; do  PKGDIR=$_PKGDIR GITDIR=$_GITDIR upkg "$2"; shift; done ;;
	l|list) while [ ! -z "$2" ]; do PKGDIR=$_PKGDIR lpkg "$2"; shift; done ;;
	q|query) while [ ! -z "$2" ]; do PKGDIR=$_PKGDIR qpkg "$2"; shift; done ;;
	r|remove) while [ ! -z "$2" ]; do PKGDIR=$_PKGDIR rpkg "$2"; shift; done ;;
	s|sync) while [ ! -z "$2" ]; do  PKGDIR=$_PKGDIR GITDIR=$_GITDIR spkg "$2"; shift; done ;;
	c|create|src|compile|make|source) PKGDIR=$_PKGDIR cpkg "$2" "$3" "$4" ;;
	sq|syncquery) while [ ! -z "$2" ]; do PKGDIR=$_PKGDIR GITDIR=$_GITDIR spkg --query "$2" ; shift ; done ;;
	h|help) echo -e "i|install) install package\nu|update) update package\nl|list) list package\nq|query) query package\ns|sync) copy over package file into pkgdir from the git repo (gitdir)\nc|create) make a package\nsq|syncquery) sync + query" ;;
	*) echo "Invalid option." ;;
esac
rm $_lock
