#!/bin/bash

PKGDIR="${FPKG_ROOT}/pkg"
DESTDIR="${FPKG_ROOT}/"

while [ ! -z "$1" ]; do	
	pkg_version=$(qpkg "$1")
	if [ $? -ne 0 ]
	then
    		echo $pkg_version
    		exit 1
	fi

	cd "$DESTDIR"
	zstd -qcd "$PKGDIR/$1-$pkg_version.tar.zst" | tar vxf - --same-owner
shift
done
