#!/bin/bash
$_shaviagit=$(openssl dgst -sha256 -r $1.sha256)
$_shaviafile=$(openssl sha $1)
if [ $_shaviagit = $_shaviafile ]
	echo "$_shaviagit = $_shaviafile"
else
	echo "$_shaviagit != $_shaviafile"
	echo "sha256 mismatch!"
	echo "Error 4"
	exit 4
fi
