#!/bin/bash

REPO="https://github.com/Ohio2/frepo"
PKGDIR="${FPKG_ROOT}/pkg"
GITDIR="${FPKG_ROOT}/git"
if [ "$#" -eq 0 ]; then
	echo "No arguments supplied."
fi
if [ ! -d $GITDIR ]; then
	git clone $REPO $GITDIR
fi

while [ ! -z "$1" ]; do
	find $GITDIR -regex ".*/$1-[a-z.0-9]*.tar.zst" -type f -printf "%f\n" | sort -V | tail -n 1

	src=$(find $GITDIR -regex ".*/$1-[a-z.0-9]*.tar.zst" -type f -printf "%f\n" | sort -V | tail -n 1)

		case $1 in
			--query) cp "$GITDIR/$src" $PKGDIR ; qpkg "$1" ;;
			*) cp "$GITDIR/$src" $PKGDIR || exit 1 ;;
		esac
shift
done
