#!/bin/bash

REPO="https://raw.githubusercontent.com/Ohio2/frepo/master"
PKGDIR="${FPKG_ROOT}/pkg"
GITDIR="${FPKG_ROOT}/git"
if [ ! -d $GITDIR ]; then
	git clone $REPO
fi

src=$(find $GITDIR -regex ".*/$1-[a-z.0-9]*.tar.zst" -type f -printf "%f\n" | sort -V | tail -n 1)



while [ ! -z "$1" ]; do
	case $1 in
		--query) cp "$GITDIR/$src" $PKGDIR ; qpkg "$1" ;;
		*) cp "$GITDIR/$src" $PKGDIR ;;
	esac
done
