#!/bin/bash

PKGDIR="${FPKG_ROOT}/pkg"
DESTDIR="${FPKG_ROOT}/"
TEMPDIR=$(mktemp -d)  

while [ ! -z "$1" ]; do
	version1=$(qpkg "$1")
	version2=$( PKGDIR=$TEMPDIR spkg "$1" | PKGDIR=$TEMPDIR qpkg "$1")
	if [ ! "$version1" = "$version2" ]; then
		PKGDIR="${FPKG_ROOT}/pkg" ipkg "$1"
	else
		echo "Up to date"
	fi
shift
done
