#!/bin/bash

while [ ! -z "$1" ]; do
	version1=$(qpkg "$1")
	version2=$(FPKG_ROOT=`mktemp` spkg "$1" | zstd -d | tar -xf | PKGDIR=$FPKG_ROOT qpkg $1)
	if [ ! $version1 = $version2 ]; then
		PKGDIR=$FPKG_ROOT ipkg "$1"
	else
		echo "Up to date"
	fi
done
shift
